name: corextensions
description: Many helpful extensions to the core classes like string and iterable.
version: 1.0.1
homepage: https://github.com/pete-g00/corextensions

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  trotter: ^1.2.0
  collection: ^1.14.13

dev_dependencies:
  pedantic: ^1.9.0